### PR TITLE
refactor: migrate `SendStream` to ES6 classes

### PR DESCRIPTION
**Pull request by mon-jai**
#### Checklist

- [x] run `npm run test` and `npm run benchmark` (There is no benchmark script in this package)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added (There are no changes affecting the API)
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

---

This pull request migrates `SendStream` to ES6 classes.

### Note

- I have done my best to maintain the original code formatting.
- All tests and lint checks pass successfully after implementing these changes.

### Changes Made

- Migrated `SendStream` to ES6 classes.
- Replaced `||` with `??` (nullish coalescing operator) wherever appropriate.
- Removed `|| false` which was redundant (`(etag && ifRange.indexOf(etag) !== -1) || false` ➡️ `(etag && ifRange.indexOf(etag) !== -1)`).

### Changes to Consider

- Utilize ES2022 private properties for private methods and properties (`_acceptRanges` ➡️ `#acceptRanges`, `hasTrailingSlash()` ➡️ `#hasTrailingSlash()`).

### CODE REVIEW

**Comment by mon-jai** [comment]
The change is minimal when whitespace changes are hidden.

image

**Review by gurgunday — COMMENTED** [review]
It looks fine but some maintainers do not like the idea of refactoring to classes for no reason, which is understandable as it may introduce subtle bugs

**Review by mcollina — CHANGES_REQUESTED** [review]
I'm -1 for that reason. You can also see a Proxy creeping in to be feature compatible.

**Comment by gurgunday** [comment]
Closing as it's no longer feasible to extend `Stream` and do such a refactor

But thanks for the effort

**Pull request closed without merging**
