### PR TITLE
Removed test folder from the package

### PR DESCRIPTION
**Pull request by mikhail-g**
There was a strange issue when building with bazel the lib wdio-vscode-service which has a dependency on @fastify/send. It breaks on the path with non-ASCII char U+2603 ☃ node_modules/@fastify/send/test/fixtures/snow ☃/index.html

A workaround for this: `rm -rf node_modules/@fastify/send/test` in `postinstall` script

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mikhail-g** [comment]
To test the change
1. run `npm pack`
2. unzip `fastify-send-2.1.0.tgz`
3. open `package` folder
Result: see that `test` folder is not included in the package

**Review by Fdawgs — CHANGES_REQUESTED** [review]
Please see https://github.com/fastify/skeleton/issues/42#issuecomment-1208090783

**Comment by mcollina** [comment]
I think a better way to fix this is to have that directory dynamically created in the tmp folder.

**Comment by Uzlopak** [comment]
Maybe it is better to report this upstream as this could be a source of error anyway.

**Review by Uzlopak — CHANGES_REQUESTED** [review]
I think this should be addressed upstream first.

**Comment by mikhail-g** [comment]
> I think this should be addressed upstream first.

@Uzlopak, do you mean at https://github.com/fastify/fastify/blob/main/.npmignore ?

**Comment by mikhail-g** [comment]
The test failure is not relevant to the change at `CI / test / Test (21, ubuntu-latest`
```
Run actions/setup-node@v4
  with:
    node-version: [2](https://github.com/fastify/send/actions/runs/6959139610/job/18936272961?pr=59#step:3:2)1
    always-auth: false
    check-latest: false
    token: ***
Attempting to download 21...
Not found in manifest. Falling back to download directly from Node
Error: Unable to find Node version '21' for platform linux and architecture x6[4](https://github.com/fastify/send/actions/runs/6959139610/job/18936272961?pr=59#step:3:4).
```

**Comment by Uzlopak** [comment]
No. This is an issue with bazel and wdio-vscode-service. So report this issue to bazel.

**Comment by kibertoad** [comment]
I'd say that it needs to be addressed in both places. It needs to be reported to Bazel, but we also shouldn't be breaking our users either.

**Comment by mikhail-g** [comment]
@Uzlopak I got your point. I also contacted bazel before. 

But my point is:
1. Having folders with whitespaces is the name is unusual practice and some other libs/frameworks could fail while working with them. So it will limit the application of this lib in those cases without giving any additional value
2. Adding `send` as a dependency I never intend to run it's tests or use them in any other way. So removing the folder will make this lib lighter, which is preferable

**Comment by Uzlopak** [comment]
anyway.

this PR should create the folder when testing and not ignore it in npmignore as @mcollina mentioned.

**Comment by mikhail-g** [comment]
Is there any reason why this lib should have `test` folder in the package?

**Comment by Uzlopak** [comment]
Yes, we like to ship them with the npm packages.

**Comment by mikhail-g** [comment]
> Yes, we like to ship them with the npm packages.

but why? is there any purpose for that?

**Comment by Uzlopak** [comment]
You can read all about it [here](https://github.com/fastify/help/issues/834)

**Pull request closed without merging**
