### PR TITLE
remove debug

### PR DESCRIPTION
**Pull request by Uzlopak**
@mcollina Maybe it makes sense to keep debug, maybe you dont like it? 
Please close unmerged if debug should stay.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — COMMENTED** [review]
You can replace it with `const debug = require('util').debuglog` if you don't want extra dependency.

**Comment by mcollina** [comment]
let's do that.

**Comment by Uzlopak** [comment]
Didnt know that! Awesome.

**Review by kibertoad — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
